name: "tftidy"
description: "Install tftidy - Remove transient blocks (moved, removed, import) from Terraform files"
author: "mkusaka"

branding:
  icon: "scissors"
  color: "purple"

inputs:
  version:
    description: "Version of tftidy to install (e.g. v1.2.3 or latest)"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Determine platform
      id: platform
      shell: bash
      env:
        RUNNER_OS_VALUE: ${{ runner.os }}
        RUNNER_ARCH_VALUE: ${{ runner.arch }}
      run: |
        case "${RUNNER_OS_VALUE}" in
          Linux)   os=linux ;;
          macOS)   os=darwin ;;
          Windows) os=windows ;;
          *)       echo "::error::Unsupported OS: ${RUNNER_OS_VALUE}"; exit 1 ;;
        esac
        case "${RUNNER_ARCH_VALUE}" in
          X64)   arch=amd64 ;;
          ARM64) arch=arm64 ;;
          *)     echo "::error::Unsupported architecture: ${RUNNER_ARCH_VALUE}"; exit 1 ;;
        esac
        if [ "${os}" = "windows" ]; then
          ext=zip
        else
          ext=tar.gz
        fi
        echo "os=${os}" >> "${GITHUB_OUTPUT}"
        echo "arch=${arch}" >> "${GITHUB_OUTPUT}"
        echo "ext=${ext}" >> "${GITHUB_OUTPUT}"

    - name: Resolve release tag
      id: resolve
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        ACTION_REPO: ${{ github.action_repository }}
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        if [ "${INPUT_VERSION}" = "latest" ]; then
          tag=$(gh api "repos/${ACTION_REPO}/releases/latest" --jq '.tag_name')
          if [ -z "${tag}" ]; then
            echo "::error::No releases found in ${ACTION_REPO}"
            exit 1
          fi
          echo "tag=${tag}" >> "${GITHUB_OUTPUT}"
        else
          echo "tag=${INPUT_VERSION}" >> "${GITHUB_OUTPUT}"
        fi

    - name: Download and install tftidy
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        ACTION_REPO: ${{ github.action_repository }}
        RESOLVED_TAG: ${{ steps.resolve.outputs.tag }}
        RESOLVED_OS: ${{ steps.platform.outputs.os }}
        RESOLVED_ARCH: ${{ steps.platform.outputs.arch }}
        RESOLVED_EXT: ${{ steps.platform.outputs.ext }}
      run: |
        asset="tftidy_${RESOLVED_OS}_${RESOLVED_ARCH}.${RESOLVED_EXT}"
        dest="${RUNNER_TEMP}/tftidy"
        mkdir -p "${dest}"
        gh release download "${RESOLVED_TAG}" \
          --repo "${ACTION_REPO}" \
          --pattern "${asset}" \
          --dir "${dest}"
        if [ "${RESOLVED_EXT}" = "zip" ]; then
          unzip -o "${dest}/${asset}" -d "${dest}"
        else
          tar -xzf "${dest}/${asset}" -C "${dest}"
        fi
        chmod +x "${dest}/tftidy" 2>/dev/null || true
        echo "${dest}" >> "${GITHUB_PATH}"
